language:
  # The default language
  # used for console and players that don't have a specific language specified
  default: "english"

  # Path to file that stores player-languages
  db: "./languages.yml"

  # Path to directory where language translations will be stored
  translations-dir: "./gma-translations/"

maps:
  world-prefix: "map-"

  # Path to the directory containing the available maps
  db: "./maps/"

queue:
  # Default waiting time in seconds
  wait-time: 60

  # Time to wait if a game is completely full
  full-wait-time: 5

  # If set to true: countdowns will be displayed in a boss bar to all players
  # If set to false: countdowns will still apply, but they won't be visible
  display-countdowns: true

visibility:
  # Tags to add to messages to send them in "public" game channel
  # Otherwise default chat will be just team chat
  public: [ "@a", "@all", "@e", "@everyone" ]

  # Determines if a team channel exists
  allow-team-chat: true

team:
  # Determines if friendly fire is enabled
  friendly-fire: false

  # Determines if player collisions count for teams
  team-collision: false

  # If set to false team prefixes won't be visible in front of player names
  display-prefix: true

  # The format in which prefixes will be rendered
  # Use "$label" as a placeholder for the team name
  prefix-format: "$label <gray>|</gray> "

# Enable / Disable different features of the plugin
features:
  commands:
    api: true
    join: true
    quit: true
    start: true
    forcemap: true
    language: true
    spectate: true
    map: true
    privategame: true

  handlers:
    queue: true
    connection: true
    gameEnd: true
    visibility: true
    respawn: true
    scoreboard: true